### ISSUE TITLE
表单input怎么实现ajax验证

### ISSUE THREAD

**Issue by Motorcure** [Tencent/weui.js#100]
貌似现在只能正则验证，是否可以做远程验证，还是只能在表单提交时处理

**Comment by BearJ** [comment]
@Motorcure 是的，checkIfBlur是没有这个接口。不过如果是上述情况，可以不调用checkIfBlur，而是手动添加blur事件，然后先weui.form.validate(‘父层的selector’)，然后过了以后发起远端检验。比如：
```javascript
weui.form.validate('.parent-weui-cell', function (error) {
    if (!error) {
        // ajax远程校验...

        // 如果校验不通过
        $('.parent-weui-cell').addClass('weui-cell_warn');
        weui.topTips('远程校验失败');
    }
});
```

**Comment by Motorcure** [comment]
@BearJ 这个方法是可以解决，我的本意是想做实时校验，而不是提交时校验，体验不同

**Comment by BearJ** [comment]
@Motorcure 这个就是实时校验了，是绑blur事件哦~

**Comment by Motorcure** [comment]
@BearJ 代码是使用了JQuery或者Zepto吧，还是weui原生就支持$

**Comment by BearJ** [comment]
@Motorcure 原生支持$
