### ISSUE TITLE
关于表单输入项失去焦点时，正则验证的一个问题

### ISSUE THREAD

**Issue by Swain9** [Tencent/weui.js#101]
weui.form.checkIfBlur("#form", regexp);
var regexp = {
        regexp: {
            MOBILE: /^1(3[0-9]|4[57]|5[0-35-9]|7[0135678]|8[0-9])\d{8}$/
        }
}
验证手机号码的时候，如果输入了一个减号（-），失去焦点检测就失效了。

**Comment by BearJ** [comment]
好的，我看看~
