### ISSUE TITLE
关于多列选择器的onChange事件

### ISSUE THREAD

**Issue by qichhhhh** [Tencent/weui.js#104]
先上代码

                weui.picker([{ label: 1, value: 1 }], [{ label: 2, value: 2 }], {
                    onChange: function (result) {
                        console.log(result);
                        console.log(result[0]);
                        console.log(result[1]);
                        console.log("--------");
                    },
                    id: 'picker'
                });

控制台打印的结果是
![yyyyyy](https://cloud.githubusercontent.com/assets/24191302/25115920/fd3e72cc-243b-11e7-9766-8802184c2e2c.png)
在初始化的时候触发了一次onChange事件 
但是此时获取不到result[1]

**Comment by BearJ** [comment]
v.1.1.2 fix~
