### ISSUE TITLE
actionSheet如果列表太长，没法滚动？

### ISSUE THREAD

**Issue by docikaci** [Tencent/weui.js#105]
actionSheet如果列表太长，没法滚动，是不是给个最大高度80%之类的，还有默认高亮一个怎么整，谢谢！

![image](https://cloud.githubusercontent.com/assets/7788102/25116125/5611c0ba-243d-11e7-8ec9-18716e8b49f1.png)

**Comment by BearJ** [comment]
@docikaci 你可以通过样式改写它，这种情况比较少，所以就没在代码上体现，尽量精简代码~

**Comment by docikaci** [comment]
目前我覆盖了默认样式，overflow:auto;maxlength: 90%;可以了

但是怎么默认高亮呢？ 谢谢

**Comment by BearJ** [comment]
那就在这个列表展现之后，找到你的元素，加一个自己的类？
