### ISSUE TITLE
ios中input标签加入capture="camera"不能选择文件的问题

### ISSUE THREAD

**Issue by ddengy** [Tencent/weui.js#106]
在ios中input标签加入capture="camera"直接弹出相机，不能选择文件。在一些安卓机型中不加入capture="camera"无法选择相机。

**Comment by ddengy** [comment]
最近才出现的问题。以前可以正常用的

**Comment by BearJ** [comment]
@ddengy 那可能要判断一下平台之后再加这个属性了
