### ISSUE TITLE
pc和安卓调起上传延时特别长

### ISSUE THREAD

**Issue by Agzer0** [Tencent/weui.js#107]
在安卓和pc上调起来有很长的延时，多点几次后会好一些，ios上没问题

**Comment by supersheep09** [comment]
一般大家默认是这么用的，<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" capture="camera" multiple="" />
这样调起确实会慢，建议  accept="image/*"  改成  accept="image/gif,image/jpeg,image/jpg,image/png"  会速度快很多。

**Comment by BearJ** [comment]
@supersheep09 这个我们之前也是这样子的，只是在部分安卓机会出现不能选，所以才用image/*    T_T
