### ISSUE TITLE
建议 form 部分的validate, checkIfBlur兼容方法调用验证

### ISSUE THREAD

**Issue by supersheep09** [Tencent/weui.js#112]
正则不能满足于所有的验证情况的， 比如输入框1的值需要根据输入框2的判断是否符合要求；又比如身份证，完全可以根据一定规则去判断是否乱填的，而不是简单满足于正则的判断。
而且还有人提出要实时ajax验证，也同时满足。
应该可以让验证更灵活的一点。

**Comment by BearJ** [comment]
@supersheep09 嗯嗯，是有这种需求，但需求量不大，如果真的需要如此复杂的配置的话，那可以使用额外的第三方库了（比如[validate.js](http://rickharrison.github.io/validate.js/)）。weui.js里的表单验证是基于较为通用和简单的校验而设置。如果是ajax验证的话，就需要手动监听blur事件来自己实现，相信这个并不难。这里倒是可以考虑把 显示报错 和 隐藏报错 的方法开放~

**Comment by BearJ** [comment]
v.1.1.2 优化
