### ISSUE TITLE
建议扩展prompt

### ISSUE THREAD

**Issue by heii** [Tencent/weui.js#120]
如题~

**Comment by BearJ** [comment]
@heii 因为weui的设计没有prompt，所以库里也是没有的~如果你需要，可以用dialog来实现~

**Comment by zhoukekestar** [comment]
我也找了一大圈 prompt，没找到，感觉就是一个简单的功能，可以的话，添加一个的话，可以方便开发者。

**Comment by BearJ** [comment]
@zhoukekestar 抱歉回复晚了。因为我们这里没有对应的设计，所以暂时无法添加哈~

**Comment by zhoukekestar** [comment]
@BearJ prompt 从标准设计上确实不好归纳进去, 用 dialog 会更灵活. 能理解哈~ anyway, 感谢回复
