### ISSUE TITLE
想给 weui 写一个  Vue 的插件配置，遇到点问题

### ISSUE THREAD

**Issue by zaxlct** [Tencent/weui.js#121]
看完了 Vue 关于插件的文档后，准备配置一下 weui ，理想中我能这么使用 `weui` ：`Vue.weui.alert()`

开始在不改变 weui 源码的思路下，尝试在项目里这么引入：
```
import 'weui'
import weui from './weui.js'
console.log(weui)  // underfined

// TODO 配置插件
xxx
```
提示是 underfined

不改变源码的思路是不是不行？
谢谢。

**Comment by BearJ** [comment]
@zaxlct 直接import也报undefined？

**Comment by zaxlct** [comment]
@BearJ 
是啊

**Comment by BearJ** [comment]
@zaxlct 那是不是引用的路径有问题

**Comment by zaxlct** [comment]
@BearJ 我放到同级的目录引入，肯定没问题吧。。
`import weui from './weui.js'`

**Comment by BearJ** [comment]
@zaxlct 抱歉回复晚了。现在还有问题不？或者你可以直接引用cdn的地址试试？

**Comment by zaxlct** [comment]
@BearJ 感谢回复，问题解决了：）
