### ISSUE TITLE
ios微信浏览器下actionSheet选项跳转链接，actionSheet不能正常消失

### ISSUE THREAD

**Issue by zouliang073** [Tencent/weui.js#127]
在actionSheet的选项中，执行location.assign('url')，跳转到另外一个页面然后浏览器返回，actionSheet没有消失，并且有的选项不能正常触发。这个问题在web开发工具和安卓下面不会出现。

使用setTimeout延迟跳转可以解决这个问题。

**Comment by BearJ** [comment]
建议加一下延迟，不排除跳到另一个页面后，当前页面的进程被阻止了，导致actionSheet的hide没有执行完毕
