### ISSUE TITLE
uploader组件居然不兼容自家的qq浏览器？

### ISSUE THREAD

**Issue by gtyd** [Tencent/weui.js#131]
环境：iPhone6s，iOS10.3.2
使用手机qq浏览器，点击拍照后有问题，通过fiddler监听不到ajax请求

**Comment by BearJ** [comment]
@gtyd 看看有没有报错？

**Comment by gtyd** [comment]
@BearJ 😭，当时项目紧张，你没回复，我们自己解决了：把自动上传置为false，重写onQueued方法，在uploadCustomFileList.forEach中调自己写的ajax-load，很是无奈

**Comment by BearJ** [comment]
@gtyd 好吧，我看看还有没有别的报错样例
