### ISSUE TITLE
weui.alert

### ISSUE THREAD

**Issue by wamdy** [Tencent/weui.js#134]
weui.alert/dialog方法点击确定时，页面元素已经被移除，所以无法取到窗体中元素的值，建议修改为处理完onclick事件后，再隐藏窗体

**Comment by qichhhhh** [comment]
var alertDom = weui.alert('手动关闭的alert', function(){
    return false; // 不关闭弹窗，可用alertDom.hide()来手动关闭
});

wiki中有这么一种用法 可能可以满足你的需求

**Comment by wamdy** [comment]
有看到这个方法：
weui.alert("<input type='password' id='password'>",function() {alert($("#password").val());return false;});
，但是没有用

**Comment by BearJ** [comment]
@wamdy 用新版试试呢？

**Comment by alextzh** [comment]
好像先执行return false 了
