### ISSUE TITLE
toast没有简单版本

### ISSUE THREAD

**Issue by zmapleshine** [Tencent/weui.js#135]
有时候需要一个简化版的提示来告知用户当前的状态，而不是弹出一个大的方形提示在中间，类似于在微信里面当你丢失了网络连接时底部有一栏提示的样子。

**Comment by progrape** [comment]
目前没有，需要 [WeUI](https://github.com/Tencent/weui) 这里有了，这里才能加上

**Comment by mjt412885604** [comment]
可以加一个弱提示toast模块, 不然每次自己要自己单独封装一个弱提示

**Comment by BearJ** [comment]
那这里等WeUI跟上了再加上

**Comment by gaoqiang19514** [comment]
> 那这里等WeUI跟上了再加上

一年过去了。。。

**Comment by progrape** [comment]
您好，设计层面暂时不支持。
