### ISSUE TITLE
使用Cascade作省市县选择器的时候,一次加载那么多的数据是不是不现实

### ISSUE THREAD

**Issue by NothinkingGao** [Tencent/weui.js#139]
使用Cascade作省市县选择器的时候,一次加载那么多的数据是不是不现实,作者是否考虑暴露异步加载数据借口呢

**Comment by BearJ** [comment]
@NothinkingGao 如果只是省市县，数据其实不大，一次性加载完还能缓存。而如果分开加载，多个请求反而会影响体验，所以我们内部的用法都是一次性加载的。当然，异步加载可以作为后期扩展，只是目前还没有这个接口~

**Comment by arronf2e** [comment]
@NothinkingGao 求一份完整省市县数据

**Comment by deepkolos** [comment]
@arronf2e npm i china-area-data --save-dev

**Comment by BearJ** [comment]
嗯嗯，可以参考楼上了
