### ISSUE TITLE
weui.confirm和alert不能调用？

### ISSUE THREAD

**Issue by evidwong** [Tencent/weui.js#140]
var alert = weui.alert('hello');
alert.hide(function(){
    weui.alert('world');
});

var confirm =weui.confirm('确定要删除吗？', function(){
			 	$.post('url', {'id': id}, function(data, textStatus, xhr) {
			 		if (data.errcode==0) {

			 			confirm.hide(function(){
				            weui.alert(1111);
				        });
			 		}else{
			 			confirm.hide(function(){
				            weui.alert(2222);
				        });
			 		}
			 	},'JSON').error(function() {
			 		confirm.hide(function(){
				            weui.alert(333333);
				        });
			 	});
			 }, function(){
			 	// 
			 });

调用不了

**Comment by BearJ** [comment]
@evidwong 是的，不能同时调用的，必须先hide掉一个才行

**Comment by progrape** [comment]
您好，请参考 #61
