### ISSUE TITLE
使用WEUI如何实现页面中其它控件或内容的不同屏幕适配？

### ISSUE THREAD

**Issue by stevenkaiwang** [Tencent/weui.js#141]
现有项目中，我们使用lib-flexible + REM来实现不同控件的屏幕适配。 
1. 是否WEUI 也能支持 与lib-flexible集成，在自定义的控件中使用REM？
2. 或者说，WEUI 不使用REM的情况下，推荐开发者使用什么机制来完成不同屏幕适配？

**Comment by BearJ** [comment]
@stevenkaiwang  weui没有用rem是因为要设置字体大小，这样会污染开发者的代码。而且，rem更多用在等比缩放的页面上，weui面向的更多是功能型的页面（表单之类），而这种页面一般不是等比缩放的。所以最后我们没有使用rem。回到你的问题：
    1. weui是不支持，所以你要用的话可能需要自己做一个全局替换(把 px -> rem)
    2. 和我上面说的，适配就是用普通的布局
