### ISSUE TITLE
datePicker 显示100年大时间段响应慢

### ISSUE THREAD

**Issue by zchhaenngg** [Tencent/weui.js#143]
datePicker显示如100年这种大时间段时，响应会很慢，
       **iphone6机器上需要4-5秒（其他安卓手机如小米5很快）**

原因在于获取picker时while循环次数太多了，此方案也过于粗暴。

**Comment by wuyuweixin** [comment]
100年范围有点宽了吧.

**Comment by progrape** [comment]
目前没有做节点回收优化，节点过多的话的确会导致慢。不过100年范围，这个场景毕竟比较少。

**Comment by davecat** [comment]
我这边也是这个问题，苹果端datepicker无法调出，很卡，把时间区间改成10年，好了。。。。还有这种操作？

**Comment by davecat** [comment]
picker是否也是采用暴力循环？譬如省市区的picker，那个JSON也很大，哪位试过？没消息 我就自己试了

**Comment by BearJ** [comment]
@davecat 是的，目前还是用暴力循环
