### ISSUE TITLE
uploader 上传图片到微信公众号临时素材，一直报错没有媒体数据

### ISSUE THREAD

**Issue by zhujie1234** [Tencent/weui.js#145]
![image](https://user-images.githubusercontent.com/19203763/27669029-2eba7040-5cb7-11e7-89c1-666ba225c82e.png)
![image](https://user-images.githubusercontent.com/19203763/27669045-435df36e-5cb7-11e7-9d8d-802703dc611b.png)

**Comment by BearJ** [comment]
@zhujie1234 看看是不是fileVal的值填错了？可以看看临时素材所需要的请求格式是如何的，然后在填
