### ISSUE TITLE
actionSheet参数加上{isAndroid:false}无效

### ISSUE THREAD

**Issue by wuyuweixin** [Tencent/weui.js#146]
var that = this;
        weui.actionSheet(
            [{
                label: '摄影',
                onClick: function onClick() {
                    that.value = '摄影';
                    setTimeout(function () {
                        $("#projection").trigger('click')
                    }, 500);
                }
            }, {
                label: '不摄影',
                onClick: function onClick() {
                    that.value = '不摄影';
                    setTimeout(function () {
                        $("#projection").trigger('click')
                    }, 500);
                }
            }],
            [{
                label: '取消',
                onClick: function onClick() {
                }
            }],{isAndroid:false});

**Comment by wuyuweixin** [comment]
现在只能通过修改js来修复这个bug

**Comment by BearJ** [comment]
@wuyuweixin 新版本v1.1.2已fix~~
