### ISSUE TITLE
加上了capture="camera"在ios设备下只能拍照了,GG.

### ISSUE THREAD

**Issue by wuyuweixin** [Tencent/weui.js#147]
现在只能通过添加以下js代码解决这个问题
//修复在iPhone设备下的bug
var ua = navigator.userAgent;
var isAndroid = ua.indexOf('Android') > -1 || ua.indexOf('Adr') > -1;
if (isAndroid) {
$("#uploaderInput").attr("capture", "camera");
}

**Comment by progrape** [comment]
这不是预期的吗？

**Comment by vmvz** [comment]
我也遇到这样的问题,  android 如果不加 capture="camera", 只能单选

如果苹果加了 capture="camera", 只能拍照了

**Comment by BearJ** [comment]
@vmvz 所以这里可以分开判断一下

**Comment by HongHaiyang** [comment]
我苹果不加capture="camera" 还是只有拍照，，，报警了。。。
