### ISSUE TITLE
时间控件在IOS上卡死

### ISSUE THREAD

**Issue by garsonguo** [Tencent/weui.js#148]
用时间控件时，按照案例3操作，在ios上运行时，卡死，导致微信退出

**Comment by progrape** [comment]
什么机型、系统？是否必现？

**Comment by mrlida** [comment]
datepicker.  日期一多计算满卡死弹不出来框

**Comment by jorycn** [comment]
同样情况，iphone6s亲测，会出现原生弹窗，数据出不来，微信直接卡死，无法操作，求解决！

**Comment by jorycn** [comment]
还没有人回答么？
把事件不要绑定在input上，然后可以避免，但这个也算是组件开发的bug了吧

**Comment by BearJ** [comment]
@jorycn 请问你是怎么调用的？
