### ISSUE TITLE
gallery在zepto的tap事件种闪退

### ISSUE THREAD

**Issue by featnet** [Tencent/weui.js#149]
![wechatimg92](https://user-images.githubusercontent.com/23646120/27913400-8c84f46c-6292-11e7-9de9-35198244af63.jpeg)

如图，在zepto的tap事件调用gallery，闪一下自动关闭，不放在tap事件里正常。
zepto版本1.2.0

**Comment by BearJ** [comment]
在alert(1)之前加个阻止事件冒泡试试？
