### ISSUE TITLE
使用datePicker， 改了开始时间， 默认时间就不起作用了（一个页面使用了两次datePicker）， 是为什么啊

### ISSUE THREAD

**Issue by zjxlbw** [Tencent/weui.js#151]
同一个页面用了两次datePicker
![u yy 9ovh_nqco ku0k9o](https://user-images.githubusercontent.com/28038666/28006346-7a062d46-6581-11e7-9fe3-d44e70c34a75.png)
改变开始时间后， 设置默认时间就不起作用了

**Comment by BearJ** [comment]
@zjxlbw 需要在再次调用时传入不一样的id
