### ISSUE TITLE
搜索框输入汉字，有时候不能搜索的bug

### ISSUE THREAD

**Issue by kuniseichi** [Tencent/weui.js#156]
正常情况下输入汉字后右下角显示换行，但有时候变成换行的一瞬间又变回确认 ，导致不能搜索
（为何不直接用搜索框，而是用换行）
如下图所示，点确认没反应，也不能搜索
https://user-images.githubusercontent.com/24471057/28517018-ab967086-7095-11e7-8214-1f11c2778a5a.PNG

**Comment by BearJ** [comment]
@Indulgecoding 确认和搜索的事件需要监听，然后对应的处理
