### ISSUE TITLE
使用picker

### ISSUE THREAD

**Issue by mangoqili** [Tencent/weui.js#157]
怎么获取picker里面的lable的值

**Comment by lt94** [comment]
@mangoqili 
```javascript
onConfirm:function(res) {
    console.log(res)
} 
```
根据打印出来数据结构采取相应的办法获取label值,两个层级应该是 *[Result,Result]*，结构类似:
```shell
[{"label":"2017年","value":2017},{"label":"10月","value":10}]
```
然后采取 *res[index].label* 的方式获取相应的*label*值

**Comment by mangoqili** [comment]
$('.type').on('click', function () {
			if(isGetType==1){
				weui.picker([{"label":"2017年","value":2017},{"label":"10月","value":10}], {
						onConfirm: function (result) {
							console.log(result[index]);
							console.log( result[index].label );
						}
					}
				);
			}
		});
输出结果：undefined
 Uncaught TypeError: Cannot read property 'label' of undefined

**Comment by lt94** [comment]
@mangoqili  这里的index是泛指索引,示例代码如下:

```javascript
        $('#time').bind('click', function () {
            weui.datePicker({
                start: new Date(),
                end: 2030,
                defaultValue: [2017, 5],
                onConfirm: function (result) {
                    var label = result[0].label + result[1].label;
                    $('#time').val(label);
                },
                id: 'time'
            })
        })
```

**Comment by mangoqili** [comment]
好的，谢谢，我已经使用循环遍历的方式获取了label的值。
