### ISSUE TITLE
地区名字过长时, Cascade-Picker 有问题

### ISSUE THREAD

**Issue by 42thcoder** [Tencent/weui.js#161]
类似 `新疆维吾尔自治区` - `恩施土家族苗族自治州` - `xx 县`, 这样名字过长时,  区域那一栏会消失

**Comment by BearJ** [comment]
这里你可以改一下样式，加入text-overflow

**Comment by BearJ** [comment]
这里你可以改一下样式，加入text-overflow

**Comment by progrape** [comment]
这种情况下建议设置截断，用 "..." 代替
