### ISSUE TITLE
datapicker如何限制只显示年和月，不显示日

### ISSUE THREAD

**Issue by huhai0403** [Tencent/weui.js#164]
dataPicker是否可以控制层级？谢谢！

**Comment by huhai0403** [comment]
建议dataPicker增加level （number，默认值：3）字段：可以选择年月日层级，1代表只显示年，2代表显示年月，默认值3代表显示年月日
代码修改weui.js第3126-3198行

`
function datePicker(options) {
                var defaults = _util2.default.extend({
                    id: 'datePicker',
                    onChange: _util2.default.noop,
                    onConfirm: _util2.default.noop,
                    start: 2000,
                    end: 2030,
                    cron: '* * *',
                    level:3
                }, options);

                // 兼容原来的 start、end 传 Number 的用法
                if (typeof defaults.start === 'number') {
                    defaults.start = new Date(defaults.start + '/01/01');
                } else if (typeof defaults.start === 'string') {
                    defaults.start = new Date(defaults.start.replace(/-/g, '/'));
                }
                if (typeof defaults.end === 'number') {
                    defaults.end = new Date(defaults.end + '/12/31');
                } else if (typeof defaults.end === 'string') {
                    defaults.end = new Date(defaults.end.replace(/-/g, '/'));
                }

                var findBy = function findBy(array, key, value) {
                    for (var i = 0, len = array.length; i < len; i++) {
                        var _obj = array[i];
                        if (_obj[key] == value) {
                            return _obj;
                        }
                    }
                };

                var date = [];
                var interval = _cron2.default.parse(defaults.cron, defaults.start, defaults.end);
                var obj = void 0;
                do {
                    obj = interval.next();

                    var year = obj.value.getFullYear();
                    var month = obj.value.getMonth() + 1;
                    var day = obj.value.getDate();

                    var Y = findBy(date, 'value', year);
                    if (!Y) {
                        Y = {
                            label: year + '年',
                            value: year,
                            children: []
                        };
                        date.push(Y);
                    }
                    var M = findBy(Y.children, 'value', month);
                    if (!M) {
                        M = {
                            label: month + '月',
                            value: month,
                            children: []
                        };
                        if(defaults.level==2||defaults.level==3){
                            Y.children.push(M);
                        }
                    }
                    if(defaults.level==3){
                        M.children.push({
                            label: day + '日',
                            value: day
                        });
                    }
                } while (!obj.done);

                return picker(date, defaults);
            }
`

**Comment by progrape** [comment]
@huhai0403 这个需求，建议使用 `picker` 自定义，自己生成年月数据。

```javascript
weui.picker([
    {
        label: '2015年',
        value: '2015',
        children: [...]
    }, {
        label: '2016年',
        value: '2016',
        children: [...]
    }, {
        label: '2017年',
        value: '2017',
        children: [...]
    }
]);
```

**Comment by wenjayliu** [comment]
哈哈 我打算改源码试试

**Comment by daraluv** [comment]
同样的需求。请问有解决方案吗

**Comment by wenjayliu** [comment]
// 生成年月数组
	function selectYM(start,defaults) {				//从几年前开始
	    var dateList = new Array();	
	    var myDate =  new Date();
	    var year = myDate.getUTCFullYear();
	    var month = myDate.getUTCMonth();
	    var startYear = year - start;					
	    var mlist = start*12+month;		

	    for(var i=month;i<=mlist;i++){
	        var date = new Date(startYear,i).Format("yyyy年M月");

	        var dataitem ={};					//生成每一项
	        dataitem.label = date;
	        dataitem.value = date;

	        dateList.push(dataitem);  			//生成数组
	     }
	        return dateList
	}

	// 生成当前年月
	var dataTime = new Date().Format("yyyy年M月");
	// console.log(dataTime)

// 单列picker
// 普通选择器
$(document).on('click', '.ymm_input', function () {
// document.querySelector('#pickerBtn').addEventListener('click', function () {
		var self = $(this);
    weui.picker(
    	selectYM(2),
    	{
        defaultValue: [dataTime],
        className: 'custom-classname',
        onConfirm: function (result) {

            console.log(self.html())
            self.html(result[0].label)

        },
        id: 'picker'
    	}
    );
});
