### ISSUE TITLE
uploader图片上传有个问题

### ISSUE THREAD

**Issue by BruceHong666** [Tencent/weui.js#168]
jpg图片头格式不标准时，会有异常，我这边临时处理是这样的：

// 获取图片的orientation ref to http://stackoverflow.com/questions/7584794/accessing-jpeg-exif-rotation-data-in-javascript-on-the-client-side 
function getOrientation(buffer) {
    var view = new DataView(buffer);
	if (view.getUint16(0, false) != 0xFFD8) {
		return -2;
    }
    var length = view.byteLength,
        offset = 2;
    try { // jpg图片头格式不标准时，解析会异常，强制返回-1，代表找不到对应的旋转标志
        while (offset < length) {
            var marker = view.getUint16(offset, false);
            offset += 2;
            if (marker == 0xFFE1) {
				if (view.getUint32(offset += 2, false) != 0x45786966) {
					return -1;
                }
                var little = view.getUint16(offset += 6, false) == 0x4949;
                offset += view.getUint32(offset + 4, little);
                var tags = view.getUint16(offset, little);
                offset += 2;
                for (var i = 0; i < tags; i++) {
					if (view.getUint16(offset + i * 12, little) == 0x0112) {
						return view.getUint16(offset + i * 12 + 8, little);
                    }
                }
            } else if ((marker & 0xFF00) != 0xFF00) {
				break;
			} else {
				offset += view.getUint16(offset, false);
            }
        }
    } catch (e) {
        return -1;
    }
    return -1;
}

所以这边强制返回 -1 让图片直接上传（不知道 -1 -2 是干嘛的 但是两个返回值都可以  所以随便选了一个）
（时间比较久了....依稀记得这个问题）

**Comment by BearJ** [comment]
@123012012104 请问是什么问题？是图片旋转不对吗？

**Comment by BruceHong666** [comment]
@BearJ 大兄dei 这个问题出在上传图片文件的时候出错，并非旋转的问题。当时的文件也找不到了...  祝好运
