### ISSUE TITLE
在iOS上tap反应迟钝

### ISSUE THREAD

**Issue by JaminQ** [Tencent/weui.js#171]
iOS上由于系统机制导致触摸事件会有200ms的延迟（好像是这么多吧，忘了），建议对tap的处理使用touchend事件处理，click事件会有延迟

**Comment by progrape** [comment]
@JaminQ 这个是移动端 web 开发通用的问题，直接使用 `touchend` 代替 `click` 事件也有问题，按住一段时间松开手也会触发，不符合 `click` 的预期。建议使用 fastclick 这个库的处理方案：https://github.com/ftlabs/fastclick
