### ISSUE TITLE
js中文乱码

### ISSUE THREAD

**Issue by pingink** [Tencent/weui.js#174]
buttons:[{label:"纭畾",type:"primary",onClick:r.default.noop}],isAndroid:i},n)   https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js 文件在浏览器打开中文乱码，使用的时候也会出现中文编码异常的情况。

**Comment by progrape** [comment]
@pingink CDN 的响应头 Content-Type 缺少了 charset=utf-8 声明导致直接打开的时候出现乱码，script 引入 应该展示到界面的应该是正常的。我们尝试一下加上 charset=utf-8 声明。

**Comment by pingink** [comment]
嗯嗯，我下载本地项目用的时候发现这个问题。
