### ISSUE TITLE
gallery 如何隐藏/去除 ‘删除’ 图标？

### ISSUE THREAD

**Issue by luxiaowu** [Tencent/weui.js#177]

**Comment by BearJ** [comment]
@luxiaowu 目前还没发去掉

**Comment by zzh3319** [comment]
+1

**Comment by zzh3319** [comment]
setTimeout(() => {
        document.getElementsByClassName("weui-gallery__del")[0].style.display =
          "none";
      }, 0);

**Comment by goodzhangbobo** [comment]
楼上点赞，亲测可用。谢谢！

**Comment by progrape** [comment]
谢谢解答
