### ISSUE TITLE
window.showErrorTips怎么不能用啊

### ISSUE THREAD

**Issue by cbk808a** [Tencent/weui.js#180]
`weui.form.showErrorTips({
    ele: document.getElementById("xxxInput")
    msg: 'empty'
});`

我用的这个地址
https://res.wx.qq.com/open/libs/weuijs/1.0.0/weui.min.js

**Comment by BearJ** [comment]
@cbk808a 用个最新的版本？https://res.wx.qq.com/open/libs/weuijs/1.1.2/weui.min.js

**Comment by cbk808a** [comment]
THX， 可以用了
