### ISSUE TITLE
uploader图片压缩质量quality参数无效？

### ISSUE THREAD

**Issue by huhai0403** [Tencent/weui.js#181]
情景：设置quality：0.8，上传200K图片一张，上传成功后服务器上对应的图片大小为160k左右，修改quality：0.2，发现上传后的图片仍然为160K。
调试：通过研究weui.js源码，打断点发现相关方法确实执行了，没有问题
请问这里是什么问题呢？

**Comment by jiafulu** [comment]
同问

**Comment by deepkolos** [comment]
如果不是通过修改分辨率的话来实现压缩大小的话, 设置quality：0 应该是会图片变为0px*0px , 如果是通过一些图片压缩算法实现, 这个quality只是参考值 , 比如再PS保存png的时候会提示选择图片质量程度1~10 ( 记得好像是

**Comment by BearJ** [comment]
嗯嗯，如楼上所说
