### ISSUE TITLE
关于使用uploader的疑问

### ISSUE THREAD

**Issue by hipudding** [Tencent/weui.js#184]
请问：
1. uploader自动上传后如何在后台实现删除，上传的文件名都已经使用uuid或者时间戳的方式更改，如何知道用户删除了哪张照片。
2. 目前手动上传是将用户选择的照片逐一上传，这样整个页面提交的时候如何能保证原子性。也就是如果其中有文件传输失败，如何将本次上传的图片撤销。
3. 上传图片如何与本次的提交关联起来，我的页面是一个信息采集页面，有问题也有多张图片，图片是分开上传的，我如何和页面的数据进行关联，就是我怎么知道哪些图片是同一批上传的。

更新：
http://blog.csdn.net/qq873113580/article/details/71128915
找到一个解决办法。

谢谢

**Comment by BearJ** [comment]
1. 可以按帖子的方法实现
2. 目前都是直接上传的，暂时无法撤销一次所有图片的操作。你可以在前面图片上传成功的后台返回的id记下来，然后再发请求让后台删除对应的图片
3. 同上，需要后台给你它收到的图片的id，这个id是后台的id，不是前段的id
