### ISSUE TITLE
建议 toast 组件增加一个 hide 方法手动关闭

### ISSUE THREAD

**Issue by ReedSun** [Tencent/weui.js#185]
现在 `toast` 只能通过设置 `duration` 来关闭自身，建议像 `loading` 组件那样增加 `hide` 方法手动触发关闭。

**Comment by BearJ** [comment]
@ReedSun 因为设计理念问题，所以这里toast是故意不加手动关闭的方法的~

**Comment by progrape** [comment]
`toast` 的设计就是用来展示简单的消息，一小段时间后自动关闭。如果需要展示信息，但手动关闭，建议使用 `alert`。
