### ISSUE TITLE
uploader某些手机的兼容问题

### ISSUE THREAD

**Issue by hVenus** [Tencent/weui.js#186]
华为P10 Plus ,android7.0，微信6.5.16,
程序在微信的公众号里。
点uploader，弹出的选择界面里，会默认弹出菜单“打开文件”，文件列表默认是最近访问的文件。
“打开文件”菜单里有几项：“最近”，“图片”，“下载内容”，“图库”，“文件管理”。
此时，选择“最近”，“图片”这两项列表里的图片，界面是没有任何反应，似乎应该是没有选中图片。
“图库”，“文件管理”这两个列表里的图片是可以正常上传。

另外，有人反应IOS系统，点uploader只能拍照，不能选择图片。

VIVO Y51Tl  andorid 5.1.1 微信6.5.16  一切正常。

我这问题，有人遇到过吗？

还有个现象，P10Plus是没有拍照选项的。 VIVO Y51Tl 是可以选拍照还是文档的。

用官网示例试了也是这问题。并不是我程序没写好。

**Comment by hVenus** [comment]
OPPO r9m 也是一样，点了图片之后没有反应。

**Comment by BearJ** [comment]
@hVenus 这应该和input的属性有关。试试加个`capture="camera"`

**Comment by poilla** [comment]
我在华为手机上也遇到了这个问题，在“图片”列表里选择图片无效果，选择“图库”里的图片就有效果

**Comment by loddit** [comment]
`<input type="file"/>` 的  `capture="camera"` 会默认调起手机拍照。
`accept="image/*"` 可以解决选项中没有拍照的问题。

**Comment by progrape** [comment]
谢谢解答～
