### ISSUE TITLE
你们这教程，怎么说... ... 太烂

### ISSUE THREAD

**Issue by lixiaosuo** [Tencent/weui.js#193]
我JS，css算熟悉的。API跟说明要相对全，一般不需要看源码。

你们给出来得weui的相关介绍例子，真他妈考验耐心，浪费时间。我TM一路查着源码下来的！

做得很大一个产品，文档能能写好一点。能查你们这破鸡巴文档的人，MB谁他妈没给过你们钱去买公众号，企业号？真TM当自己开源的 Picker，你妈js+html+css结合在一起就没人说得清！

**Comment by BearJ** [comment]
@lixiaosuo 请问你是遇到什么问题吗？
