### ISSUE TITLE
Picker从右侧滑入

### ISSUE THREAD

**Issue by yuzifu** [Tencent/weui.js#202]
看demo是从底部向上滑入的，但我模仿写出的却是从右侧向左滑入的，什么地方可以调整为跟demo一样的效果？我的代码如下：
`    $('.page__bd').on('click', '#showPicker', function () {
      weui.picker([{
          label: 'Item 1',
          value: 0
      }, {
          label: 'Item 2',
          value: 1
      }, {
          label: 'Item 3',
          value: 2
      }], {
          onChange: function (result) {
              console.log(result);
          },
          onConfirm: function (result) {
              console.log(result);
          }
      });
  });`

**Comment by BearJ** [comment]
这里看不出问题，是不是样式上你修改了动画函数？

**Comment by sushuier** [comment]
从右侧向左 划入的，你可能是用到了   example.css  里面的  那个 路由弹层的入场动画，@keyframes a{} 和 @keyframes b{}  你可以搜一下

**Comment by yuzifu** [comment]
谢谢，是少引入了样式
