### ISSUE TITLE
picker label 内部可以自定义么？

### ISSUE THREAD

**Issue by iijx** [Tencent/weui.js#203]
需求上有可能要在 label 上加个“说明”，或者加个小图标之类的提示。比如下图这样的：
![2017-12-05 9 39 47](https://user-images.githubusercontent.com/19170733/33585726-acb696fc-d9a0-11e7-8a4e-77cba59a63f4.png)

目前似乎做不了这个

**Comment by BearJ** [comment]
嗯嗯，是的，目前实现不了。。
