### ISSUE TITLE
weui.loading显示进度提示，接着hide再跳转到新页面，再从新页面返回，在ios上，返回后loading又在页面上

### ISSUE THREAD

**Issue by rwsbillyang** [Tencent/weui.js#206]
问题描述：用weui.loading('loading...')显示loading动画后，在setTimeout中hide并跳转到其它页面，再从其它页面返回，则仍有个静止的loading显示。只在iPhone上存在此问题，Android和PC上均无问题；

具体如下：
1. 点击页面确认按钮，显示loading进度提示，2秒后跳转到新页面，如百度；
2.再从百度中返回；
3.原页面仍显示一个静止不动的loading提示；

目前替代方案是：不用weui.js，直接使用weui.css的toast，然后用zepto的fadeIn和fadeOut来控制。但麻烦得多。

[测试HTML页面](http://test.bxzhiku.com/weixin/testweui.html)
页面中js代码：
```
     <script type='text/javascript'>
        $('#myclick').on('click', function() {
                console.log("click...");
		var loading = weui.loading('loading...');
		setTimeout(function() {
			loading.hide();
			location.href="http://www.baidu.com";
		}, 2000);
		
		return false
	})
   </script>
```

**Comment by BearJ** [comment]
可以在hide里面传个回调，然后在里面做跳转。

**Comment by baidi123** [comment]
回调请问有代码演示一下吗 我现在也遇到这个问题了 比较急

**Comment by progrape** [comment]
```javascript
loading.hide(function() {
  // 跳转逻辑
});
```
