### ISSUE TITLE
选取一张图片时列表每次都出现两张同一样的图片，怎么回事，

### ISSUE THREAD

**Issue by LannyCodes** [Tencent/weui.js#209]
点击+图标选取图片触发时间我用网上的如下代码：
`$uploaderInput.on("change", function(e){
      var src, url = window.URL || window.webkitURL || window.mozURL, files = e.target.files;
      for (var i = 0, len = files.length; i < len; ++i) {
        var file = files[i];
        if (url) {
          src = url.createObjectURL(file);
        } else {
          src = e.target.result;
        }
        $uploaderFiles.append($(tmpl.replace('#url#', src)));
      }
    });
`请问是怎么回事，急急，求解答

**Comment by BearJ** [comment]
是不是change事件触发了两次？或者你打个断点看看到底是哪里被调用了两次？
