### ISSUE TITLE
onProgress方法中上传进度只有0%和100%

### ISSUE THREAD

**Issue by weborockfeller** [Tencent/weui.js#211]
需求要求上传时显示百分比进度，但onProgress方法中上传进度只有0%和100%，中间的进度是没有的，求解

**Comment by BearJ** [comment]
这个是监听了xhr的progress事件，是需要后台配合的

**Comment by weborockfeller** [comment]
/* 图片自动上传 */
var uploadCount = 0, uploadList = [];
var uploadCountDom = document.getElementById("uploadCount");
weui.uploader('#uploader', {
    url: 'http://' + location.hostname + ':8002/upload',
    auto: true,
    type: 'file',
    fileVal: 'fileVal',
    compress: {
        width: 1600,
        height: 1600,
        quality: .8
    },
    onBeforeQueued: function(files) {
        if(["image/jpg", "image/jpeg", "image/png", "image/gif"].indexOf(this.type) < 0){
            weui.alert('请上传图片');
            return false;
        }
        if(this.size > 10 * 1024 * 1024){
            weui.alert('请上传不超过10M的图片');
            return false;
        }
        if (files.length > 5) { // 防止一下子选中过多文件
            weui.alert('最多只能上传5张图片，请重新选择');
            return false;
        }
        if (uploadCount + 1 > 5) {
            weui.alert('最多只能上传5张图片');
            return false;
        }

        ++uploadCount;
        uploadCountDom.innerHTML = uploadCount;
    },
    onQueued: function(){
        uploadList.push(this);
        console.log(this);
    },
    onBeforeSend: function(data, headers){
        console.log(this, data, headers);
        // $.extend(data, { test: 1 }); // 可以扩展此对象来控制上传参数
        // $.extend(headers, { Origin: 'http://127.0.0.1' }); // 可以扩展此对象来控制上传头部

        // return false; // 阻止文件上传
    },
    onProgress: function(procent){
        console.log(this, procent);
    },
    onSuccess: function (ret) {
        console.log(this, ret);
    },
    onError: function(err){
        console.log(this, err);
    }
});
请问如何在上述方法中监听xhr的progress事件？

**Comment by BearJ** [comment]
@weborockfeller 这里
```javascript
onProgress: function(procent){
    console.log(this, procent);
}
```

**Comment by weborockfeller** [comment]
可是这是返回的只有0和100%，你有实际用过吗？

**Comment by BearJ** [comment]
@weborockfeller https://jsfiddle.net/qahs40r6/12/
