### ISSUE TITLE
datepick窗口弹出来之后，点击微信导航上 返回 按钮，返回到上一页，窗口依然存在

### ISSUE THREAD

**Issue by meidongwei** [Tencent/weui.js#214]
datepick窗口弹出来之后，点击微信导航上 返回 按钮，返回到上一页，窗口依然存在，请问这个问题有什么办法可以解决吗？我试着在另一个页面初始化的时候，获取picker窗口对象，然后设置 style.display = 'none'，这样可以解决问题，但是新问题是：再次进入日期选择页面，点击弹出窗口的按钮，无效了，不显示窗口了。

**Comment by BearJ** [comment]
最新版里面可以在onClose里加入回调，回调里跳转页面

**Comment by meidongwei** [comment]
@BearJ 你好，你说的这个不能解决我的问题呀，我的问题是：窗口弹出来之后，点击浏览器的返回按钮，返回到上一个页面之后，date窗口依然没有关闭。你说的在onClose里加入回调，然后里面跳转，这怎么跳转，可以提供一个简单的demo或示例代码吗？

**Comment by BearJ** [comment]
@meidongwei 嗯嗯，是我理解错了。那应该是你监听到浏览器的返回操作之后，需要手动关闭date，我想你应该是单页面应用吧，所以是需要自己手动调一下datepicker的hide方法

**Comment by mjt412885604** [comment]
是因为你的spa页面导致的
