### ISSUE TITLE
如何解决uploader在安卓手机下无法一次选择多张图片

### ISSUE THREAD

**Issue by guzhehang** [Tencent/weui.js#216]

**Comment by BearJ** [comment]
这样写试试？`<input class="weui-uploader__input" type="file" accept="image/*" capture="camera" multiple="" />`

**Comment by guzhehang** [comment]
<input class="weui-uploader__input" type="file" accept="image/*" capture="camera" multiple="" />，魅族pro7，经测试，无论是点击还是长按，还是无法一次选择多张图片。

**Comment by guzhehang** [comment]
按照你这样写，魅族pro7，经测试，无论是点击还是长按，还是无法一次选择多张图片。

**Comment by BearJ** [comment]
@guzhehang 试试`multiple="multiple"`，如果还不行，那只能说是系统做了限制了

**Comment by guzhehang** [comment]
@BearJ 魅族Pro7，红米note4，荣耀畅玩6A，试过都不行不行，看来是系统限制，哎

**Comment by allen1024git** [comment]
不是系统限制，是微信限制了。使用系统自带的浏览器访问页面时可以正常多选，在微信中访问就不行
