### ISSUE TITLE
picker弹框出来的数据怎样设置默认选中某一个？

### ISSUE THREAD

**Issue by daijinghao** [Tencent/weui.js#217]
请问picker弹框显示的数据是默认选中中间的数据么？怎么设置默认选中某一个？

**Comment by daijinghao** [comment]
单列picker

**Comment by BearJ** [comment]
@daijinghao 可以用default参数

**Comment by daijinghao** [comment]
@BearJ 您好，之前试过了，没有起作用
var arr = [{
            label: '全上海',
            value: 0,
			disabled: true // 不可用
        }, {
            label: '长宁区',
            value: 1
        }, {
            label: '闵行区',
            value: 2
        },{
            label: '嘉定区',
            value: 3
        }, {
            label: '杨浦区',
            value: 4
        }];
    $('#showPicker').on('click', function () {
        weui.picker(arr, {
   className: 'custom-classname',
   container: 'body',
   defaultValue: arr[1],

请问有具体的演示示例么，wiki里面的贴出来没有起效

**Comment by daijinghao** [comment]
@BearJ 难道是用的js版本低了？

**Comment by BearJ** [comment]
@daijinghao defaultValue是传值，看你是想默认选长宁区，那么你试试用`defaultValue: [1]`

**Comment by daijinghao** [comment]
@BearJ 好的，谢谢，可以了！理解错误，以为是传具体某个数组进去的
