### ISSUE TITLE
picker在iphone8,ios11下错位的问题

### ISSUE THREAD

**Issue by isaaxite** [Tencent/weui.js#220]
手机平台以及版本：
![image](https://user-images.githubusercontent.com/25907273/35840262-162f1148-0b30-11e8-995b-7c328e05f3bd.png)
问题如标题，picker选项在ip8的ios11+的详细下，滑动会出现移位，看一看见滑到最后，都没有到达最后一下，矩形选中款是停留倒数第二项的，项数越多以为越大。详细请看下图：
![image](http://sl-cdn.hingyin.com/o_1c5kiihi01tms8om11hk19h59el7.gif)

**Comment by BearJ** [comment]
@issaxite 是不是重新设置了picker的font-size，目前如果是改了的话，会发生这种现象

**Comment by issaxite** [comment]
这个问题是只有i8有问题，在我的i6或者其他同事的安卓机并没有出现这个问题
