### ISSUE TITLE
picker 不支持动态配置？？

### ISSUE THREAD

**Issue by lq0910** [Tencent/weui.js#222]
picker 不支持动态配置？？ 我的itmes是动态生成的，每次更新后，选项内容还是第一次的数据，请问有法子解决？ 还是说插件本身不支持动态配置。

**Comment by yangjisen** [comment]
vue:
export default {
   data() {
      return {
            pickers: [
                    { label:'选项1', value:1 },
                    { label:'选项2', value:2 },
            ]
         }
     },
      methods: {
           weui.picker(this.pickers, {
                    onConfirm: function (result) {
                        console.log(result)
                    },
                    id: 'pickers'
                });
     }
}

不会排版,将就看吧

**Comment by BearJ** [comment]
@lq0910 你传一个不一样的id就可以了
