### ISSUE TITLE
datePicker如何实现只显示年月

### ISSUE THREAD

**Issue by FireLiujie** [Tencent/weui.js#224]
如题

**Comment by Genuifx** [comment]
```
import weui from 'weui.js/dist/weui.js'
```

然后手动把x下面的代码注释
![image](https://user-images.githubusercontent.com/10156994/39284259-f95b0f38-4944-11e8-9a7f-09c0283076a7.png)

**Comment by lyj-js** [comment]
depth：2

**Comment by progrape** [comment]
您好，可以指定 `depth` 为 2 。
