### ISSUE TITLE
请问 如何在特地情况下 去掉表单校验?

### ISSUE THREAD

**Issue by ljq-aaron** [Tencent/weui.js#230]
例如目前我好几个表单  其中有一个是配送方式 比如我选了上门自取 就不需要输入快递地址了. 请问怎么动态去掉验证?我是点击提交按钮就获取input的val值  接着提交ajax发送数据到后端.  那怎么动态不验证这个东西?试了几个方法都不行啊

**Comment by progrape** [comment]
您好，移除掉快递的 DOM 结构即可。
