### ISSUE TITLE
picker滚动事件判断分支疑问

### ISSUE THREAD

**Issue by Myoursky** [Tencent/weui.js#244]
https://github.com/Tencent/weui.js/blob/b05877857a14354dcefdae6d98b762784a32598f/src/picker/scroll.js#L189-L193

此处如果end和start相差小于10特殊处理的是为了解决什么问题呢，试了下直接执行stop(end - start)也没什么问题，是不是我有什么情况没考虑到，还望解答，谢谢。

**Comment by sklthegoodman** [comment]
如果没有这个判断，快速点击的时候有可能也会被视为滑动。
