### ISSUE TITLE
为何不直接提供datetimePicker呢？

### ISSUE THREAD

**Issue by 263613093** [Tencent/weui.js#248]
需要选择日期+时间，但是目前只支持日期，时间需要自己额外用picker做，本来一部的操作现在需要两步骤来完成了，扩展了一个datetimePicker但是效率太低了

**Comment by sklthegoodman** [comment]
有的，请查阅：
https://github.com/Tencent/weui.js/blob/master/docs/component/picker.md#datePicker

**Comment by ramen-curator** [comment]
> 有的，请查阅： https://github.com/Tencent/weui.js/blob/master/docs/component/picker.md#datePicker

里面并没有发现 关于“日期+时间”（即“年/月/日 时:分”）的相关说明。
@263613093 
最后是怎么解决的呢？依然是使用自己扩展的datetimePicker吗？现在有更好的办法了吗？
