### ISSUE TITLE
在Safari浏览器上picker报错,Type Error

### ISSUE THREAD

**Issue by 263613093** [Tencent/weui.js#251]
Safari打开https://weui.io/weui.js/ 打开开发人员工具报错如下
example.js:2075  TypeError: Type error
导致在Safari端picker无法使用，但是IOS移动端无这个问题
相同问题在safari下页面调用weui.picker。。也会有Type Error错误

**Comment by haoxiaokun** [comment]
我也遇到了。请问解决没
