### ISSUE TITLE
微信开发者工具 alert[取消][确定]按钮不能触发

### ISSUE THREAD

**Issue by pkkgu** [Tencent/weui.js#257]
微信开发者工具 v1.02.1810250 
alert[取消][确定]按钮不能触发

**Comment by pkkgu** [comment]
confirm
dialog
都不能触发

**Comment by chaegumi** [comment]
https://github.com/Tencent/weui.js/issues/259#issuecomment-451710500

**Comment by 410919244** [comment]
没人解决？

**Comment by 410919244** [comment]
解决了  "weui": "^1.1.3",
    "weui.js": "^1.1.4",
这两个加了才可以
