### ISSUE TITLE
picker联动动态更新视图

### ISSUE THREAD

**Issue by chenlin19970520** [Tencent/weui.js#269]
在滚动时，触发onchange获取下一级的数据，然后是会更新的，需要再次滚动到这里才会更新

**Comment by chenlin19970520** [comment]
picker滑动时去看子列表的数组有没有存在而且长度超过0，有就会显示，没有就会隐藏，但是onchange是在滑动之后去获取的数据，这样的话就不能及时更新了。必须等到下次滑动，又去查看子列表的数组

**Comment by jinlinupup** [comment]
你好，我目前也是这个问题，请问解决了吗？@[chenlin19970520](/chenlin19970520)

**Comment by chenlin19970520** [comment]
我是把需要的数据一次性加载进去，就好了。

**Comment by jinlinupup** [comment]
好吧。我这边不能这样进行操作哦，因为数据量太大了

**Comment by chenlin19970520** [comment]
我是用来选择省市区的

**Comment by jinlinupup** [comment]
我这边也差不多，需求是省市区镇村5级联动。。

**Comment by chenlin19970520** [comment]
这个picker的深度只有3级

**Comment by sklthegoodman** [comment]
你好，目前还没有动态加载。
而且，级联过多切需要动态加载，不建议全部加到一个picker，而是通过多个picker来实现。
