### ISSUE TITLE
weui alert 内容在Android微信上不自动换行

### ISSUE THREAD

**Issue by runhwguo** [Tencent/weui.js#275]
求帮助。
message是服务器response回来的一个字符串。
weui.alert(message, {
                    title: '提示',
                    buttons: [{
                      label: '确定',
                      type: 'primary'
                    }]
                  })

**Comment by runhwguo** [comment]
测试发现是必现，如果复现不了，请在此留言。

**Comment by sklthegoodman** [comment]
请提供一下机型、系统信息和weui.js的版本信息。
以及
这个message变量具体是什么？
