### ISSUE TITLE
weui.js 一系列诡异的样式问题

### ISSUE THREAD

**Issue by zipeijun** [Tencent/weui.js#281]
npm 安装 weui 版本号 ^1.1.4
无论是使用项目中自带的样式还是 https://res.wx.qq.com/open/libs/weui/1.1.3/weui.min.css
都会出现诡异的问题、例如 actionSheet 旋转出现、弹窗组件不显示之类
在更换 https://res.wx.qq.com/open/libs/weui/1.1.3/weui.css 之后问题消失。
请检查下 min 版本的 css

**Comment by sklthegoodman** [comment]
你好，请提供一下代码片段，或者检查一下是否是样式污染。
