### ISSUE TITLE
 安卓微信无法从相册选择照片

### ISSUE THREAD

**Issue by shiliuxing** [Tencent/weui.js#285]
<input id="uploaderCustomInput" class="weui-uploader__input" type="file" accept="image/*" multiple="">

安卓版微信7.0.4 选择相册照片，无法选中，请问是什么问题呢？

**Comment by BruceHong666** [comment]
你的代码是不是设置了 accept?
```
 <input type="file"accept="image/gif, image/jpeg" />
```

去掉即可：
```
 <input type="file" accept="image/*" />
```
or
```
<input type="file" />
```

应该是安卓手机对图片做了优化吧

**Comment by shiliuxing** [comment]
<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" multiple />

**Comment by shiliuxing** [comment]
<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" multiple />
这样没错呀，不分安卓手机会出现这个问题，无法从相册选中图片，官方的demo也是一样

**Comment by shiliuxing** [comment]
`<input id="uploaderInput" class="weui-uploader__input" type="file" accept="image/*" multiple />`

这样没错呀，部分安卓手机会出现这个问题，无法从相册选中图片，官方的demo也是一样

**Comment by progrape** [comment]
#98
