### ISSUE TITLE
comfirm 关闭时 alert 组件无法显示

### ISSUE THREAD

**Issue by yyh2219182230** [Tencent/weui.js#287]
在使用 comfirm 组件的时候，在确定的回调事件触发时，调用 weui.alert 无法显示

`
weui.confirm('是否确认提交？', function(){
    weui.alert('温馨提示');
});
`

alert 弹框 不会出现。

**Comment by xCss** [comment]
同遇到，楼上的兄弟怎么解决的？

:confused:

**Comment by yyh2219182230** [comment]
用定时器，或者回调方法




------------------ 原始邮件 ------------------
发件人: "Nine"<notifications@github.com>; 
发送时间: 2019年8月12日(星期一) 下午5:57
收件人: "Tencent/weui.js"<weui.js@noreply.github.com>; 
抄送: "迟暮 indulgeヽ"<2219182230@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Tencent/weui.js] comfirm 关闭时 alert 组件无法显示 (#287)




同遇到，楼上的兄弟怎么解决的？
 
😕

**Comment by progrape** [comment]
https://github.com/Tencent/weui/issues/791
