### ISSUE TITLE
关于picker在onChange时的重要疑问

### ISSUE THREAD

**Issue by sushuier** [Tencent/weui.js#292]
picker在onChange时，动画很流畅没毛病；
但是，
用example中的单列选择来讲：
默认选中第3项 “的士票”，此时我滚动容器，切换到飞机票，然后点击mask层关闭控件；
然后再次点击picker时，picker控件的默认选中值不应该还是最初的“的士票”吗？因为我没有点击确定，只是随意切换看了下其他的选项啊，为什么重新点开的时候，默认选中的值是 onchange后的“飞机票”呢？
这种设计是出于什么考虑？

**Comment by sushuier** [comment]
为了避免 onchange时 改变了 控件默认选中项的问题，就必须每次动态存，动态传id，代码：
![微信截图_20190829162505](https://user-images.githubusercontent.com/22663393/63923976-104fd900-ca7a-11e9-8e7e-dabd70dd6d2f.png)

**Comment by BearJ** [comment]
@sushuier 每次点击给picker传参`id`，然后值是随机，这样可以重置picker。保留上次的选项的原因是为了避免用户不小心把picker关掉以致需要重新选择。
