### ISSUE TITLE
表单验证不可用

### ISSUE THREAD

**Issue by 490626721** [Tencent/weui.js#307]
按照文档操作表单验证，一直提示输入正确的格式

**Comment by zhyblack** [comment]
你的weui css 什么版本？

**Comment by 490626721** [comment]
<link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/2.0.1/weui.min.css"&gt;
<script type="text/javascript" src="https://res.wx.qq.com/open/libs/weuijs/1.2.1/weui.min.js"&gt;</script&gt;
使用的这个版本



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhy_black"<notifications@github.com&gt;; 
发送时间: 2020年3月20日(星期五) 晚上7:50
收件人: "Tencent/weui.js"<weui.js@noreply.github.com&gt;; 
抄送: "VZVZA"<490626721@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Tencent/weui.js] 表单验证不可用 (#307)





 
你的weui css 什么版本？

**Comment by heii** [comment]
form里加个novalidate="true"就可以用了

```<form class="weui-form" novalidate="true" id="form">```
