### ISSUE TITLE
datePicker怎么支持时分的选择？

### ISSUE THREAD

**Issue by docikaci** [Tencent/weui.js#38]
能否提供一个日历的插件呀，也很常用呢，
不光是年月日，还要时分秒，可以配置
谢谢

**Comment by BearJ** [comment]
@docikaci 日期和时间一起选的话，屏幕小就会放不下。建议是分开选。那么，因为时间picker相对简单，所以这里自己实现即可。（00-12和00-59的数组）

**Comment by docikaci** [comment]
@BearJ 
![image](https://cloud.githubusercontent.com/assets/7788102/21842854/8d4e8e2a-d823-11e6-93a9-746d41c4c797.png)

像这种体验就特别好呀

项目里不想都引入（只用一个功能，有点浪费）
这种也是比较常见的，还是希望考虑下哦

**Comment by BearJ** [comment]
@docikaci 我们更建议这种实现方式：http://codepen.io/bearyan/pen/ggmRrx?editors=1010

**Comment by sushuier** [comment]
感觉 确实有必要  年月日 时分 在一起的，因为 如果 让你选 开始时间 和结束时间，拆开的话  就要点4次，体验并不会很好

**Comment by BearJ** [comment]
@sushuier 目前我们限制了最多4列，那把这个限制放开吧，这样就可以自己实现上述5列的年月日时分。但是因为weui的设计上最多允许4列，否则在iphone4/5之类的小屏幕就太挤，所以我们并没有实现。

**Comment by BearJ** [comment]
@sushuier 这个在1.1.2就可以使用多列的了，没有限制列数哈
