### ISSUE TITLE
请问怎么在webpack环境中实现分模块引入？

### ISSUE THREAD

**Issue by aweiu** [Tencent/weui.js#51]
这个我觉得还是挺有必要的，有时候就只想用一点点。。
比如我想这样：
`import alert from 'weui.js/src/alert/alert'`
但是vue的webpack配置中又忽略了node_modules,所以会编译不通过，因为该模块使用了es6语法

**Comment by BearJ** [comment]
@aweiu 好的，这个后期可以优化一下。目前更建议用cdn的版本哈~~
