### ISSUE TITLE
uploader使用疑问

### ISSUE THREAD

**Issue by BoreyLee** [Tencent/weui.js#65]
uploader中的图片列表能不能一次性上传，而不是多少次上传？

**Comment by BearJ** [comment]
@BoreyLee 为什么要这样做呢？万一中途失败了呢。。。

**Comment by gtyd** [comment]
@BoreyLee 可以啊，你在图片库里面一次多选几张不就可以了！

**Comment by Iamlars** [comment]
同问，能否提供可用于 Formdata 方式上传的表单对象？

**Comment by BearJ** [comment]
@Iamlars uploader的`type`参数填`file`即可
