### ISSUE TITLE
表单中正则验证顺序问题，初始化滚动条问题， 对表单验证不支持未来事件

### ISSUE THREAD

**Issue by slingsky** [Tencent/weui.js#66]
1、源码1570行 应该优先进行正则的判断 再次进行value为空的判断才对，否则当正则验证可以为空的时候导致无法通过。

2、源码2530行  初始化滚动条时，进行了三次没有缓存并且没有默认值传入 并且默认值不为空的时候才进行初始化，导致初始化滚动条时出现异常，应该是没有缓存或者有传入值存在并且传入的值为有效参数
 if (lineTemp[level] === undefined || (defaults.defaultValue && defaults.defaultValue[level] !== undefined))

3、表单验证 只对已经在页面中存在了的 有required属性的表单进行了blur focus的绑定（源码1713行），而对于未来事件并没有任何效果，导致使用的时候有了很多的局限性，希望能对未来事件也可以进行相应的操作

**Comment by BearJ** [comment]
@slingsky 赞！谢谢你宝贵的建议：
- 1、下个版本优化
- 2、这个是因为我们想在没有缓存的时候才读取default，如果有缓存的情况下就不读取了。因为有时候picker第二次点开是需要记录上一次的操作的，而不是显示default。如果你想再次点开是读取default的话，可以传入不同的id参数
- 3、这个可以有，看下个版本能否带上。目前你可以这样做，在新增的元素上增加一个父层，然后再次调用`weui.form.checkIfBlur('父层的selector',...)`
