### ISSUE TITLE
在vue的组件中引入，weui.searchBar('#searchBar')没有反应，

### ISSUE THREAD

**Issue by 270556660** [Tencent/weui.js#70]
`<template>`
<div class="weui-tab__panel">
    <div class="search">
        <div class="weui-search-bar" id="searchBar">
            <form class="weui-search-bar__form">
                <div class="weui-search-bar__box">
                    <i class="weui-icon-search"></i>
                    <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="搜索" required="">
                    <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
                </div>
                <label class="weui-search-bar__label" id="searchText">
                    <i class="weui-icon-search"></i>
                    <span>搜索</span>
                </label>
            </form>
            <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
        </div>
    </div>
</div>
</template>
<script>
import 'weui';
import weui from 'weui.js';
export default {
    data() {
        return {
            name: "测试",
        }
    },
    created() {
        weui.alert('alert');//有弹窗
        weui.searchBar('#searchBar');//没有反应
    }
}
</script>

**Comment by BearJ** [comment]
@270556660 searchBar是需要自己引入dom的哈~

**Comment by machao1990** [comment]
@BearJ 同问，使用uploader时也遇到这个问题了，仅提供一个selector无法见到效果，但是文档中也没有说明该怎么布置dom啊~望解答

**Comment by machao1990** [comment]
@BearJ 已经解决了

**Comment by BearJ** [comment]
@machao1990 的确，文档需要加强，谢谢提醒哈~

**Comment by BearJ** [comment]
v.1.1.2 fix~

**Comment by chenmingwei** [comment]
我服务器要返回什么结构的结果呢
