### ISSUE TITLE
datePicker的end参数有缺陷

### ISSUE THREAD

**Issue by izyh** [Tencent/weui.js#73]
datePicker的end参数指定为双十之前的日期，显示的可选范围不包含end参数指定的日期，当end参数指定为双十及之后的日期，显示的可选范围则包含end参数指定的日期！

**Comment by progrape** [comment]
@izyh hello，请问“双十”日期，指的是哪个日期？方便我们重现一下bug，谢谢

**Comment by izyh** [comment]
“双十”是指10月10号，datePicker的可选范围在start参数（包含）和end参数（不一定包含）之间，当end参数指定10月10号之前的日期时，datePicker的可选范围是不包含end参数的指定日期的，当end参数指定10月10号及之后的日期时，datePicker的可选范围包含该指定日期。比如说我start参数为2017-3-15，end参数为2017-10-09，那么我的datePicker可选范围是2017.3.15到2017.10.08（包含这两个指定日期）；如果我的start参数为2017-3-15，end参数为2017-10-10，那么我的datePicker可选范围是2017.3.15到2017.10.10（包含这两个指定日期）。也就是说datePicker可选范围做不到以10月9号结束。

**Comment by progrape** [comment]
![image](https://cloud.githubusercontent.com/assets/4652816/23932567/d8543614-0973-11e7-9034-18c6c9bdd478.png)

http://codepen.io/progrape/pen/KWqjLw?editors=1010

@izyh 你好，我做了个测试，指定 end 日期为 `2017-10-09` 的时候，是可以选择到 9号 这一天的，但是我们发现如果 end 日期写成 `2017-10-9` （9前面少了0），就选不到 9号这天，只能选到 8 号这天，这应该是个 bug，我们处理 fix 一下。你可以通过在前面补上 0 来暂时规避这个 bug～

**Comment by izyh** [comment]
好的，谢谢。我也发现这个问题了。如果不严格按照`xxxx-xx-xx`(即年4位，月4位，日4位)来指定`start`和`end`的话，在IOS下还会有更严重问题，直接导致整个页面崩溃掉，可能是内存泄露导致，希望也可以修复一下。不过我目前都严格按照`xxxx-xx-xx`来指定`start`和`end`了，已规避了该bug，只是在不知道该bug情况下很难排查。

**Comment by longweilol** [comment]
你们知道着怎么一打开选择器 就是定位到当前时间么 就是默认是当前时间

**Comment by sushuier** [comment]
@longweilol   自己获取当前日期时间，然后拼成一个数组  传到组件里

**Comment by BearJ** [comment]
v.1.1.2 fix~
