### ISSUE TITLE
官方demo及单页应用中picker打开之后按浏览器返回键，picker不会消失

### ISSUE THREAD

**Issue by beckyzhan** [Tencent/weui.js#76]
![qq 20170309192334](https://cloud.githubusercontent.com/assets/10825353/23748377/673e260c-04fe-11e7-86dd-b19bb5f77fec.png)

**Comment by BearJ** [comment]
@beckyzhan 好的，是个bug，谢谢哈~

**Comment by HAxiaoha** [comment]
@beckyzhan  解决了吗？我也遇到这个问题了
