### ISSUE TITLE
ActionSheet里如果label是html标签的话，点击标签部分不会正确的触发选择

### ISSUE THREAD

**Issue by freeforver** [Tencent/weui.js#79]
`例如我的actionSheet的选项的label都是<span class="xxx">1</span>这样的，那么选择的时候点击空白区域没问题，点击span就不会正确的选择到这个选项。`

**Comment by BearJ** [comment]
@freeforver 我试了下貌似没问题，你的调用方式是？

**Comment by freeforver** [comment]
`weui.actionSheet([
    {
        label: '<span class='xxx'>问询</span>',
        onClick: function () {
            $(_input).val('问询');
        }
    }, {
        label: '<span class='yyy'>投诉</span>',
        onClick: function () {
            $(_input).val('投诉');
        }
    }, {
        label: '<span class='zzz'>其它</span>',
        onClick: function () {
            $(_input).val('其它');
        }
    }
], [
    {
        label: '取消',
        onClick: function () {
            console.log('取消');
        }
    }
]);`
版本是v1.1.1，点击actionSheet选项的空白区域没问题，但是点击文字部分就会有问题...

**Comment by BearJ** [comment]
@freeforver 也是没问题。。你的span的样式是？

**Comment by freeforver** [comment]
没有。。就一个color.....
那我再研究研究吧.....

**Comment by BearJ** [comment]
@freeforver 如果有DEMO我能更好的帮你分析~~

**Comment by AnyGong** [comment]
确实是这样。远吗有一处有bug，我手动改了本地。
