### ISSUE TITLE
mac chrome 用了example里的代码，可以选择文件，但是无上传动作

### ISSUE THREAD

**Issue by klend** [Tencent/weui.js#80]
环境：
chrome版本 41.0.2272.76 (64-bit)，macos版本：10.11.6 
问题：
chrome 的console无任何报错，输出，就是没有上传动作，其它weuijs功能正常
哪个大神给个提示，这是啥原因

**Comment by BearJ** [comment]
@klend 看看有没有发出网络请求？

**Comment by klend** [comment]
@BearJ 没有任何网络请求，反复检查代码，跟example没区别，有啥其它低级错误难道？

**Comment by BearJ** [comment]
@klend 那打个断点不断跟踪下去看看是哪里报错了？
