### ISSUE TITLE
react weui + weui.js 

### ISSUE THREAD

**Issue by weishijun14** [Tencent/weui.js#84]
//html
` <Uploader
              id="uploader"
              title="图片上传"
              maxCount={1}
              onChange={this.uploaderChange}
            />`

//js
uploaderChange = (event,files) => {
    let uploadCount = 0;
    weui.uploader('#uploader',{
      url:'http://192.168.1.135:8080/xxxxx/xxx/xxxx/xxxxxx',
      auto:true,
      type:'file',
      compress:{
        width: 1600,
        height: 1600,
        quality: 0.8
      },
      onBeforeQueued: function(
      console.log(1)
     },
    })
  }

**可以进uploaderChange (),**
**但是根本无法调用onBeforeQueued(),请问这是为什么**

**Comment by BearJ** [comment]
不要通过onChange来绑定，直接在dom准备好了之后调用：

**Comment by WynnLin** [comment]
在React该怎么使用组件？是这样么？
//import 
import { Picker } from "weui.js";
//html
<Picker items={ this.state.items } defaultValue={ [3] }/>

**Comment by WynnLin** [comment]
@BearJ 
在React该怎么使用组件？是这样么？
//import
import { Picker } from "weui.js";
//html

**Comment by BearJ** [comment]
@WynnLin 目前还没有分开引用的方式，你这样引用试试：
```javascript
import weui from 'weui.js';

weui.alert('alert');
```
