### ISSUE TITLE
picker使用

### ISSUE THREAD

**Issue by stylejinmu** [Tencent/weui.js#86]
在onChange, onConfirm回调方法里现在可以取到label、value值，如果自定义一个和label、value同级的属性，回调里不能取得这个值。是否能支持自定义属性？

**Comment by BearJ** [comment]
@stylejinmu 请问是出于什么需求呢？

**Comment by stylejinmu** [comment]
@BearJ 比如有a, b, c三个变量要在onConfirm里获取，现在的处理方法是 value='a,b,c'，然后value.split(',')获取a、b、c。这样做会有副作用，picker无法设置默认值了。所以可否加一个和label、value同级的属性，例如extraObj，变量a、b、c放在extraObj里，value则继续它自己的使命。

**Comment by BearJ** [comment]
@stylejinmu 后续版本可以优化一下~

**Comment by BearJ** [comment]
@stylejinmu 看了下，value是可以传一个对象进去的，这样就可以解决你的问题了

**Comment by jingkeyang** [comment]
一直提示picker not a function 是为什么啊 weuil.js 已经正常打包了

**Comment by BearJ** [comment]
@jingkeyang 你试试引用：https://res.wx.qq.com/open/libs/weuijs/1.1.3/weui.min.js ？
