### ISSUE TITLE
微信中网页下拉露底显示网址，为什么https://weui.io/可以屏蔽露底呢？怎么做到的

### ISSUE THREAD

**Issue by yanglz1991** [Tencent/weui.js#87]
微信中网页下拉露底显示网址，为什么https://weui.io/ 可以屏蔽露底呢？怎么做到的

**Comment by docikaci** [comment]
同问，谢谢

**Comment by BearJ** [comment]
@xiaozhicode @docikaci 是jsAPI控制的，不过这个JSAPI没有对外开放，所以外部还用不了。。。

**Comment by docikaci** [comment]
可不可以考虑对外开放啊，比如所谓认证过后的安全域名，是否可以调用api启用 下拉不露底。
我们在做企业号开发， 都是企业用户使用，他们不需要知道页面，也没有意义，下拉露底，好丑的说，
谢谢

**Comment by xiaozhicode** [comment]
在页面做下拉刷新的时候露底很难看，强烈请求开放

**Comment by merlinchen** [comment]
@BearJ  原来是不可描述的方法~
