### ISSUE TITLE
searchBar,在input为空时，点击取消，不能触发click事件

### ISSUE THREAD

**Issue by zqinmiao** [Tencent/weui.js#88]
![image](https://cloud.githubusercontent.com/assets/12278003/24235593/fe596332-0fd8-11e7-9e6e-a500aa005618.png)
在搜索框为空时，点击取消按钮不能触发绑定的click事件。输入内容了，就可以触发。
看了源码，没发现什么不对的啊。下面是searchbar对应的源码：
![image](https://cloud.githubusercontent.com/assets/12278003/24235685/65c76f3c-0fd9-11e7-9cf5-5b94a70d115e.png)

请问什么原因呢？

**Comment by BearJ** [comment]
@zqinmiao https://weui.io/weui.js/ 我试了下，木有问题呀，你是哪台设备？

**Comment by zqinmiao** [comment]
@BearJ iphone5s 系统10.2.1

**Comment by BearJ** [comment]
@zqinmiao 有没有页面可以调试？
