### ISSUE TITLE
actionSheet怎么动态传入数组，以及回调里能拿到当前item对象里的数据？

### ISSUE THREAD

**Issue by docikaci** [Tencent/weui.js#89]
比如说后台返回的数据是动态的
![image](https://cloud.githubusercontent.com/assets/7788102/24287809/137b28bc-10b6-11e7-9a3b-d866f3d33f7b.png)
想用actionSheet展示，然后点击后拿到当前一条数据，id，name之类的发送给后台。
谢谢

**Comment by BearJ** [comment]
@docikaci 扩展一下school_list，每个item增加一个onClick，然后传入actionSheet的menus即可
