### ISSUE TITLE
为什么微信浏览器上传图片拿不到type？

### ISSUE THREAD

**Issue by z042492** [Tencent/weui.js#90]
为什么微信浏览器上传图片拿不到type？

**Comment by BearJ** [comment]
@z042492 你指的是哪个type？

**Comment by zhaojianhui129** [comment]
我也遇到同样的问题，在安卓的微信浏览器中，选择某些分类的图片（如图库）获取文件的content-type值为空，无法过滤图片类型，如果去掉图片类型限制，后端就报500错误了。

**Comment by BearJ** [comment]
@zhaojianhui129 试试原文件上传，具体是把`compress`设为`false`, `type`设为`file`
