### ISSUE TITLE
uploader安卓微信浏览器中Blob方式传输问题

### ISSUE THREAD

**Issue by kumakumasan** [Tencent/weui.js#91]
uploader在后台发现已经无法正常获得文件名了，在PC和IOS上面都没问题。请问哪位可以帮助我？

**Comment by BearJ** [comment]
@kumakumasan 你可以调试看看，调试方法看：

**Comment by kumakumasan** [comment]
文件名是异常的；

**Comment by kumakumasan** [comment]
我们用这种方法调试过，通过查看tbs中的网络监听器，我们发现在请求头中，文件名失去了后缀（转义化了），而且请求头中的content-type也已经不是image格式

**Comment by BearJ** [comment]
@kumakumasan 你们是如何调用的？
