### ISSUE TITLE
datePicker使用疑问

### ISSUE THREAD

**Issue by BoreyLee** [Tencent/weui.js#92]
datePicker现在是可以选择年、月、日。能不能只显示年和月这2项，不显示日？

**Comment by BearJ** [comment]
@BoreyLee 目前来说不可以，但你可以自己组建一个数组，用普通picker来实现~

**Comment by watership** [comment]
普通picker 怎么做到联动？或者有没有刷新选项列表的方法。

**Comment by BearJ** [comment]
@watership https://github.com/weui/weui.js/blob/master/docs/component/picker.md 里面的级联picker

**Comment by yzqiang** [comment]
将depth参数设置为2

**Comment by fantingsheng** [comment]
将depth参数设置为2，就这么简单，为什么都不知道还绕着走
