### ISSUE TITLE
searchbar点击搜索时触发的事件应该怎样写？

### ISSUE THREAD

**Issue by ghost** [Tencent/weui.js#95]
我需要在搜索框输入文字，点击搜索获取数据，不知道应该怎样写，希望大神指点迷津！！！

**Comment by BearJ** [comment]
@Thomas-lee-2014 给“搜索”的按钮绑定事件，触发的时候获取一下input的value~

**Comment by Thomas-lee-2014** [comment]
谢谢，回复迟了[/抱拳]
