### ISSUE TITLE
weui.confirm和weui.alert不能放在一起用

### ISSUE THREAD

**Issue by baiyuxiong** [Tencent/weui.js#96]
```
weui.confirm('确定要取消吗？', function(){
             $.post('url',{'id':'1'},function(data){
                  weui.alert('操作成功');
            },'json');
            }, function(){
                //console.log('no')
            });
```
上面的代码weui.alert窗口不能弹出来。

下面的代码，只会alert hello，不会alert world
```
weui.alert('hello');
weui.alert('world');
```

**Comment by BearJ** [comment]
@baiyuxiong 请参考#61，这里是我们的文档写得不够明白，迟点我们会优化文档，请见谅哈。

**Comment by yuciu** [comment]
下面这种效果的弹不出alert，confirm.hide回调不行，[#61](https://github.com/weui/weui.js/issues/61)的dialog也试过不行，有好的办法吗？
```javascript
weui.confirm('确定取消吗？', function(){
    var loading = weui.loading('取消中...');
    $.post('/cancel', {id: '1'}, function(data){
        loading.hide();
        if (!data.error) {
            weui.toast('取消成功');
        } else {
            weui.alert('取消失败，原因.....');
        }
    }, 'json');
});
```

**Comment by fengqiming** [comment]
@BearJ 还是不行噢，加上之后，去到weui.alert()那里没有反应

**Comment by wolfben** [comment]
这样隐藏真是太麻烦了，建议参考下jquery weui的做法，要是多个判断，每次都的隐藏一下。

**Comment by dayu007** [comment]
现在这个方法好像又不能用了，
var confirm = weui.confirm('确定要取消吗？', function(){
    $.post('url',{'id':'1'},function(data){
        console.log(1)
        confirm.hide(function(){
            console.log(2)
            weui.alert('操作成功');
        });
       console.log(3)
    },'json');
});

只能打出1,3，hide方法进不去

**Comment by jerrybendy** [comment]
@BearJ 你好，你上面的写法仍然是有问题的（最新版本 1.1.4 下）。POST 请求返回所用的时间是未知的，很大概率下在 POST 返回之后 `confirm.hide` 的回调是不被触发的。

**Comment by jerrybendy** [comment]
找到一种封装方式可以解决这个问题：

```js
function myAlert(msg, okCallback) {
  var dialog = weui.alert(msg, function() {
    dialog.hide(okCallback || $.noop)
    return false
  })
}

```
