### ISSUE TITLE
ios下gallery图片不显示

### ISSUE THREAD

**Issue by huhai0403** [Tencent/weui.js#97]
在项目中我是用了gallery和uploader组件，安卓下gallery正常，但是在**ios下gallery图片没有显示**。
`var url = target.style.backgroundImage;    

                    url = url.slice(5,url.length-2);   

                    console.log(url);    

                    var gallery = weui.gallery(url, {   
 
                        className: 'file',    

                        onDelete: function(){   
 
                            weui.confirm(    

                                '确定删除该图片？',   
 
                                function(){    

                                    $(target).remove();    

                                });   

                            gallery.hide();   

                        }  

                    });`

**Comment by BearJ** [comment]
@huhai0403 把url  alert一下看看？我觉得可能是ios的url有问题~

**Comment by zhujie1234** [comment]
![image](https://user-images.githubusercontent.com/19203763/27717542-90d25466-5d78-11e7-8618-b82adc93bc2d.png)
 我也遇到了这种情况，这是ios环境下打出来的url
@BearJ

**Comment by zhujie1234** [comment]
和Android环境下的url格式不一样，
![image](https://user-images.githubusercontent.com/19203763/27717704-72eef034-5d79-11e7-94bf-5c832f5e39c0.png)
@BearJ 这是Android环境下的url

**Comment by zhujie1234** [comment]
而且我还发现一个问题，ios10系统都不能预览和显示，10以下系统版本都可以显示。这问题可以解决兼容吗？
@BearJ

**Comment by zhujie1234** [comment]
已经解决，是微信新版本使用内核WKWebview导致的无法加载问题，官方文档给出了解决方案。https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1483682025_enmey
碰到同类问题的朋友可以去看下。基本能解决。

**Comment by BearJ** [comment]
变化：1.2.0以下版本的JSSDK不再支持通过使用chooseImage api返回的localld以如：”img src=wxLocalResource://50114659201332”的方式预览图片。

适配建议：直接将JSSDK升级为1.2.0最新版本即可帮助页面自动适配，但在部分场景下可能无效，此时可以使用
getLocalImgData接口来直接获取数据。

。（目前JSSDk线上版本是 1.0.0 和 1.1.0，更新版本为1.2.0 ，https://res.wx.qq.com/open/js/jweixin-1.2.0.js ）
