### ISSUE TITLE
微信浏览器上传图片，不能判断图片类型

### ISSUE THREAD

**Issue by wuxuejian** [Tencent/weui.js#99]
用安卓微信浏览器上传时 onBeforeQueued回调里面 this对象的属性是类似这样的
id: 1, name: image%3A182864, lastModified: 1484454374000, lastModifiedDate: Sun Jan 15 2017 12:26:14 GMT+0800 (CST), webkitRelativePath: , size: 395610, type: , 
名字不是原名，type 没有值，
IOS版正常

**Comment by BearJ** [comment]
@wuxuejian 那应该是安卓那里的浏览器处理过导致type没了，这种确实比较坑。。不过我看name里有个image，你可以判断当没有type的时候，判断name是否有image字样
